Improves the module examples/complete
alibabacloud-automation/terraform-alicloud-ram-fc pull request #3
Opened 2021-12-20 12:57 UTC by MrWolong

2021-12-23 03:51 UTC, Wanghx0991 commented on examples/complete/README.md
> +Configuration in this directory creates RAM&FC on Alibaba Cloud.
RAM&FC -> `RAM` and `FC`

2021-12-23 03:51 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +ram_role_description = "this is my ram role"
ram_role_description = "ram_role_description"
这种命名整体修改下,规范起来

2021-12-23 03:51 UTC, Wanghx0991 commented on examples/complete/tfvars/01-update.tfvars
> +fc_service_description = "my tf unit test"
fc_service_description = "fc_service_description"

2021-12-23 03:51 UTC, Wanghx0991 commented on terratest/terraform_test.go
> +		TerraformDir: "../examples/",
../examples/complete

2021-12-23 03:51 UTC, Wanghx0991 commented on terratest/terraform_test.go
> +// An examples of how to test the simple Terraform module in examples/terraform-basic-examples using Terratest.
An example of how to test the simple Terraform module in examples/complete using Terratest

2021-12-23 03:51 UTC, Wanghx0991 commented on examples/complete/variables.tf
> +  default     = "tf unit test"
fc_service_description

2021-12-23 06:47 UTC, Wanghx0991 commented on terratest/terraform_test.go
> +// An example of how to test the simple Terraform module in examples/terraform-basic-examples using Terratest.
// An example of how to test the simple Terraform module in examples/complete using Terratest.

2021-12-24 06:15 UTC, xiaozhu36 requested changes

2021-12-24 06:15 UTC, xiaozhu36 commented on examples/complete/main.tf
> +  append_meta           = var.append_meta
上面这两个资源，可以改用 sls 的module： https://github.com/terraform-alicloud-modules/terraform-alicloud-sls/blob/master/main.tf

2021-12-24 10:52 UTC, xiaozhu36 requested changes

2021-12-24 10:52 UTC, xiaozhu36 commented on examples/complete/tfvars/01-update.tfvars
> +fc_service_description = "fc_service_description"
这里面可以改的参数跟 variable中的不一致啊

2021-12-28 02:39 UTC, xiaozhu36 requested changes

2021-12-28 02:39 UTC, xiaozhu36 commented on examples/complete/tfvars/01-update.tfvars
> +##############################################################
document 也是可以修改的吧

2021-12-30 02:18 UTC, merged